modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="wizards_reborn"
version="1.20.1-0.0.1"
displayName="Wizard's Reborn"
logoFile="wizards_reborn.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''

'''

[[dependencies.wizards_reborn]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wizards_reborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"