modLoader="javafml"
loaderVersion="[47,)"
license="GPL-2.0"

[[mods]]
modId="wizards_reborn"
version="1.20.1-0.1.1"
displayName="Wizard's Reborn"
logoFile="wizards_reborn.png"
authors='''
MaxBogomol - Developer
FoxPlane and iDark - Ukrainian localization
Kekqupap - Belarusian localization
ishi_sama - French localization
Onjerlay - OST
OnixTheCat - Deer
'''
description='''
Adds magical things
'''

[[dependencies.wizards_reborn]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wizards_reborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wizards_reborn]]
    modId = "curios"
    mandatory = true
    versionRange = "[5.2.0-beta.3+1.20.1,)"
    ordering = "AFTER"
    side = "BOTH"